name: glum_mood_tracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-146.2.beta <3.0.0"

dependencies:
  auto_route: ^7.4.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  drift: ^2.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.1
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  google_fonts: ^5.0.0
  hooks_riverpod: ^2.1.1
  image_cropper: ^5.0.0
  image_picker: ^0.8.6+2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  json_serializable: ^6.5.4
  mockito: ^5.4.2
  path: ^1.8.2
  path_provider: ^2.0.11
  riverpod: ^2.1.1
  rxdart: ^0.27.7
  sqlite3: ^1.9.1
  sqlite3_flutter_libs: ^0.5.12

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.3.2
  drift_dev: ^2.2.0+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: clem
      fonts:
        - asset: assets/fonts/clem-bold.otf
          weight: 700
        - asset: assets/fonts/clem-cbold.otf
          weight: 600
        - asset: assets/fonts/clementine.otf
          weight: 400
        - asset: assets/fonts/clem-italic.otf
          style: italic
