// Mocks generated by Mockito 5.4.2 from annotations
// in glum_mood_tracker/test/application/core/tags_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:glum_mood_tracker/domain/failures/failures.dart' as _i5;
import 'package:glum_mood_tracker/domain/models/models.dart' as _i6;
import 'package:glum_mood_tracker/infrastructure/repositories/tag_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TagRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagRepository extends _i1.Mock implements _i3.TagRepository {
  MockTagRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.TagFailure, _i2.Unit>> addTag(_i6.TagModel? tag) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTag,
          [tag],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.TagFailure, _i2.Unit>>.value(
            _FakeEither_0<_i5.TagFailure, _i2.Unit>(
          this,
          Invocation.method(
            #addTag,
            [tag],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.TagFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i5.TagFailure, _i2.Unit>> deleteTag(
          _i6.TagModel? tag) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTag,
          [tag],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.TagFailure, _i2.Unit>>.value(
            _FakeEither_0<_i5.TagFailure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteTag,
            [tag],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.TagFailure, _i2.Unit>>);
  @override
  _i4.Stream<_i2.Either<_i5.TagFailure, List<_i6.TagModel>>> watchAllTags() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllTags,
          [],
        ),
        returnValue:
            _i4.Stream<_i2.Either<_i5.TagFailure, List<_i6.TagModel>>>.empty(),
      ) as _i4.Stream<_i2.Either<_i5.TagFailure, List<_i6.TagModel>>>);
}
